# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/zynq/zynq.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq || ORIG_REF_NAME==zynq} -quiet] -quiet

# IP: bd/zynq/ip/zynq_processing_system7_0_0/zynq_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_processing_system7_0_0 || ORIG_REF_NAME==zynq_processing_system7_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_dma_0_0/zynq_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_axi_dma_0_0 || ORIG_REF_NAME==zynq_axi_dma_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_ps7_0_axi_periph_1/zynq_ps7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_ps7_0_axi_periph_1 || ORIG_REF_NAME==zynq_ps7_0_axi_periph_1} -quiet] -quiet

# IP: bd/zynq/ip/zynq_rst_ps7_0_100M_1/zynq_rst_ps7_0_100M_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_rst_ps7_0_100M_1 || ORIG_REF_NAME==zynq_rst_ps7_0_100M_1} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_smc_2/zynq_axi_smc_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_axi_smc_2 || ORIG_REF_NAME==zynq_axi_smc_2} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axi_smc_1_1/zynq_axi_smc_1_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_axi_smc_1_1 || ORIG_REF_NAME==zynq_axi_smc_1_1} -quiet] -quiet

# IP: bd/zynq/ip/zynq_axis_data_fifo_0_0/zynq_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_axis_data_fifo_0_0 || ORIG_REF_NAME==zynq_axis_data_fifo_0_0} -quiet] -quiet

# IP: bd/zynq/ip/zynq_auto_pc_0/zynq_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==zynq_auto_pc_0 || ORIG_REF_NAME==zynq_auto_pc_0} -quiet] -quiet

# XDC: bd/zynq/zynq_ooc.xdc
